"""empty message

Revision ID: 05480a31a7c1
Revises: 70187e0386d0
Create Date: 2020-11-27 02:56:06.752647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05480a31a7c1'
down_revision = '70187e0386d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_todo_modified'), ['modified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_modified'))
        batch_op.drop_column('modified')

    # ### end Alembic commands ###
