"""empty message

Revision ID: 06a72ae95995
Revises: 
Create Date: 2021-06-13 12:21:41.739536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a72ae95995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tracker_timestamp'), 'tracker', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_timestamp'), table_name='tracker')
    op.drop_column('tracker', 'timestamp')
    # ### end Alembic commands ###
