"""Add pending deletion fields to User model

Revision ID: 0e7e1c5570bc
Revises: ff4c9da3f99c
Create Date: 2025-12-24 21:53:51.644436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7e1c5570bc'
down_revision = 'ff4c9da3f99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_deletion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deletion_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deletion_requested_at')
        batch_op.drop_column('pending_deletion')

    # ### end Alembic commands ###
