"""Add OAuth columns to User model

Revision ID: 366e5694a9ad
Revises: 6793349c088c
Create Date: 2025-11-25 22:39:18.478952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366e5694a9ad'
down_revision = '6793349c088c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todo_target_date'), ['target_date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_oauth_id'), ['oauth_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_oauth_id'))
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_target_date'))

    # ### end Alembic commands ###
