"""Add API token fields to User model

Revision ID: 3e5106ee570c
Revises: 366e5694a9ad
Create Date: 2025-11-26 03:09:58.871869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5106ee570c'
down_revision = '366e5694a9ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_token'))
        batch_op.drop_column('token_created_at')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
