"""add_deleted_account_tracking_table

Revision ID: 4329e380c9c6
Revises: i1234567890
Create Date: 2025-12-04 09:51:53.427872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4329e380c9c6'
down_revision = 'i1234567890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deleted_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deleted_account_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deleted_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deleted_account_email'))

    op.drop_table('deleted_account')
    # ### end Alembic commands ###
