"""todo table

Revision ID: 70187e0386d0
Revises: 9f452c76741b
Create Date: 2020-11-23 00:01:03.328619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70187e0386d0'
down_revision = '9f452c76741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index('ix_todo_name')
        batch_op.create_index(batch_op.f('ix_todo_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_name'))
        batch_op.create_index('ix_todo_name', ['name'], unique=1)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
