"""Add KIV table

Revision ID: 7bcc476d38aa
Revises: 4329e380c9c6
Create Date: 2025-12-07 15:53:16.557367

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '7bcc476d38aa'
down_revision = '4329e380c9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KIV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_id')
    )
    with op.batch_alter_table('KIV', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_KIV_entered_at'), ['entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_KIV_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_KIV_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
    
    # Migrate existing KIV todos (status_id=9) to new KIV table
    connection = op.get_bind()
    
    # Find all todos that are currently KIV (status_id=9)
    # Query: Get the most recent tracker entry for each todo where status_id=9
    migrate_sql = """
    INSERT INTO KIV (todo_id, user_id, entered_at, is_active)
    SELECT DISTINCT 
        t.id,
        t.user_id,
        NOW(),
        1
    FROM todo t
    INNER JOIN tracker tr ON t.id = tr.todo_id
    WHERE tr.status_id = 9
    AND tr.id IN (
        SELECT MAX(id) FROM tracker 
        WHERE status_id = 9 
        GROUP BY todo_id
    )
    ON DUPLICATE KEY UPDATE is_active = VALUES(is_active)
    """
    
    connection.execute(sa.text(migrate_sql))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KIV', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_KIV_user_id'))
        batch_op.drop_index(batch_op.f('ix_KIV_is_active'))
        batch_op.drop_index(batch_op.f('ix_KIV_entered_at'))

    op.drop_table('KIV')
    # ### end Alembic commands ###
