"""todo table

Revision ID: 9be16091199b
Revises: 
Create Date: 2020-11-22 23:19:32.958147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be16091199b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.String(length=250), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_name'), 'todo', ['name'], unique=True)
    op.create_index(op.f('ix_todo_timestamp'), 'todo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_timestamp'), table_name='todo')
    op.drop_index(op.f('ix_todo_name'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
