"""Remove username column from user table

Revision ID: 9c6cb91c6f23
Revises: cbedd2ef5ed4
Create Date: 2025-11-30 15:11:02.394166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6cb91c6f23'
down_revision = 'cbedd2ef5ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    # ### end Alembic commands ###
