"""todo table

Revision ID: 9f452c76741b
Revises: d9ef517217d5
Create Date: 2020-11-22 23:26:05.170323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f452c76741b'
down_revision = 'd9ef517217d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=250), nullable=True))
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('details')

    # ### end Alembic commands ###
