"""Add terms_and_disclaimer table

Revision ID: add_terms_and_disclaimer
Revises: add_email_verified
Create Date: 2025-12-15 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'add_terms_and_disclaimer'
down_revision = 'add_email_verified'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_and_disclaimer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terms_of_use', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False, server_default='1.0'),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms_and_disclaimer')
    # ### end Alembic commands ###
