"""Add API token field to User model

Revision ID: c682ef478e45
Revises: 3e5106ee570c
Create Date: 2025-11-26 03:25:59.347849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c682ef478e45'
down_revision = '3e5106ee570c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_created_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
