"""Fix API token column - ensure api_token exists

Revision ID: d1f2e3c4b5a6
Revises: c682ef478e45
Create Date: 2025-11-26 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'd1f2e3c4b5a6'
down_revision = 'c682ef478e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add api_token column if it doesn't exist
    # This migration ensures the column exists for all database states
    # 
    # Context: 
    # - Migration 3e5106ee570c adds api_token + token_created_at
    # - Migration c682ef478e45 removes token_created_at
    # - This migration ensures api_token exists regardless of migration history
    
    # Check if column already exists before adding (handles duplicate migration scenarios)
    conn = op.get_bind()
    try:
        # Try to query the column to see if it exists
        conn.execute(sa.text("SELECT api_token FROM user LIMIT 1"))
        # Column exists, skip adding
    except Exception:
        # Column doesn't exist, add it
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('api_token', sa.String(length=255), nullable=True))
            batch_op.create_index(batch_op.f('ix_user_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    
    # Use raw SQL for safer downgrade that handles edge cases
    try:
        conn.execute(sa.text("DROP INDEX ix_user_api_token ON user"))
    except Exception:
        # Index doesn't exist or already dropped, continue
        pass
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        try:
            batch_op.drop_column('api_token')
        except Exception:
            # Column doesn't exist, continue
            pass

    # ### end Alembic commands ###
