"""todo table

Revision ID: d9ef517217d5
Revises: 9be16091199b
Create Date: 2020-11-22 23:24:13.935991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ef517217d5'
down_revision = '9be16091199b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', sa.String(length=250), nullable=True))
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###
