"""empty message

Revision ID: e8e593570299
Revises: 601cf5ecfe62
Create Date: 2021-06-09 02:12:06.374405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e593570299'
down_revision = '601cf5ecfe62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('details_html', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'details_html')
    # ### end Alembic commands ###
