"""Change todo columns to Text for encryption support

Revision ID: f8802884f95e
Revises: b435845c3539
Create Date: 2025-11-29 19:45:42.000000

This migration changes the todo table columns (name, details, details_html) from
String to Text type to accommodate encrypted data which is longer than plaintext.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8802884f95e'
down_revision = 'b435845c3539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        # Drop the index on name column first (TEXT columns can't have indexes in MySQL)
        batch_op.drop_index('ix_todo_name')
        
        # Change column types from String to Text to accommodate encrypted data
        batch_op.alter_column('name',
                              existing_type=sa.String(length=80),
                              type_=sa.Text(),
                              existing_nullable=False)
        batch_op.alter_column('details',
                              existing_type=sa.String(length=250),
                              type_=sa.Text(),
                              existing_nullable=True)
        batch_op.alter_column('details_html',
                              existing_type=sa.String(length=500),
                              type_=sa.Text(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: This downgrade will FAIL if:
    # 1. Encryption has been used - encrypted data exceeds String limits
    # 2. Any todo name > 80 chars, details > 250 chars, or details_html > 500 chars
    # Data will be truncated or the migration will fail entirely.
    # Consider backing up data before downgrading.
    with op.batch_alter_table('todo', schema=None) as batch_op:
        # Revert column types back to String
        batch_op.alter_column('name',
                              existing_type=sa.Text(),
                              type_=sa.String(length=80),
                              existing_nullable=False)
        batch_op.alter_column('details',
                              existing_type=sa.Text(),
                              type_=sa.String(length=250),
                              existing_nullable=True)
        batch_op.alter_column('details_html',
                              existing_type=sa.Text(),
                              type_=sa.String(length=500),
                              existing_nullable=True)
        
        # Recreate the index on name column (only works after converting back to String)
        batch_op.create_index('ix_todo_name', ['name'], unique=False)

    # ### end Alembic commands ###
