"""Add terms_accepted_version field to User model for terms acceptance tracking

Revision ID: ff4c9da3f99c
Revises: f3f3b7d1e30a
Create Date: 2025-12-16 00:25:49.988402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4c9da3f99c'
down_revision = 'f3f3b7d1e30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted_version', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_version')

    # ### end Alembic commands ###
