"""Add reminder fields to todo.

Revision ID: g1234567890
Revises: 9c6cb91c6f23
Create Date: 2025-12-02 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g1234567890'
down_revision = '9c6cb91c6f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('reminder_enabled', sa.Boolean(), nullable=True))
    op.add_column('todo', sa.Column('reminder_time', sa.DateTime(), nullable=True))
    op.add_column('todo', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'reminder_sent')
    op.drop_column('todo', 'reminder_time')
    op.drop_column('todo', 'reminder_enabled')
    # ### end Alembic commands ###
