"""Add timezone field to user.

Revision ID: h1234567890
Revises: g1234567890
Create Date: 2025-12-02 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h1234567890'
down_revision = 'g1234567890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(50), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE user SET timezone = 'UTC' WHERE timezone IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
