"""Add reminder notification tracking fields to Todo model.

Revision ID: i1234567890
Revises: h1234567890
Create Date: 2025-12-03 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'i1234567890'
down_revision = 'h1234567890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('reminder_notification_count', sa.Integer, nullable=True, default=0))
    op.add_column('todo', sa.Column('reminder_first_notification_time', sa.DateTime, nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE todo SET reminder_notification_count = 0 WHERE reminder_notification_count IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'reminder_notification_count')
    op.drop_column('todo', 'reminder_first_notification_time')
    # ### end Alembic commands ###
